### ISSUE TITLE
Meetup group

### ISSUE THREAD

**Issue by MylesBorins** [dancejs/Oakland#11]
So it costs around $15 a month to keep the meetup group going.  We have not been using it and I think it would be best to just close it.  We can send out a group email prior to doing so.  Should we setup a mail chimp or mandrill mailing list before closing so we can get sign ups?

The next set of dues are expected to be paid on Thursday, so we don't have much time to send out this email if we are going to do it.

/cc @bcoe @mikeal @gsilk @dshaw @linclark @nexxy

**Comment by bcoe** [comment]
I think shutting down the meetup is a good idea, I think we've got promotion pretty dialed in on the twitters.

**Comment by affinity-matrix** [comment]
:+1: I've never been that fond of the site anyway.
