### ISSUE TITLE
Dance.js Oakland, March 28th 2015

### ISSUE THREAD

**Issue by bcoe** [dancejs/Oakland#15]
I would like to propose that we have our first Oakland Dance.js of 2015, at @mikeal's new event space on March 28th 2015.

Based on conversations this week at the Sacramento JavaScript meetup, it sounds like we have some leads on sponsorship from: @samt, @emilyrose, and @bryan-m-hughes.

How does this date work for people? CC: @othiym23, @TheAlphaNerd, @gsilk?

**Comment by mikeal** [comment]
WFM, I'll make sure the space is ready.

**Comment by othiym23** [comment]
WFM. My calendar randomly tells me that that's Tim Caswell's birthday, so it can be the Special @creationix Edition of DanceJS!

**Comment by creationix** [comment]
Indeed.  I won't be able to make it, so you'll have to dance for me. :)

**Comment by affinity-matrix** [comment]
what?! no! @creationix you are literally like the best dancer I've met. You have to come!

**Comment by MylesBorins** [comment]
:+1: on date!!!

**Comment by mikeal** [comment]
Some time soon everyone should come over and setup the audio gear and the lights. If we don't have enough cords or need better anything it would be good to work it out long before the event so that we can order it.

**Comment by mikeal** [comment]
oh, and I just ordered this http://www.amazon.com/dp/B004THBG3A/ref=pe_385040_127745480_TE_item

**Comment by affinity-matrix** [comment]
fancy! let me know when you're thinking sounds good. I'm happy to come play with the lights.

**Comment by bcoe** [comment]
Awesome @mikeal, perhaps we could come next weekend and set some stuff up?
- rd.io wants to sponsor, we should get a ticket page up as soon as possible, @mikeal do you mind tossing something up on ti.to again? my preference would be to have sponsorship tickets, and free tickets (so that we can gauge numbers).
- @emilyrose you said Spark might be able to sponsor for $500 as well?

I'm super pumped!

**Comment by MylesBorins** [comment]
I�d be up for meeting next weekend.  Railroad earth is playing at The Fox theatre saturday night, so I�ll already be across the bridge!

I highly suggest checking it out if you like the blue grass thing :D  If you are going to do it grab tickets off stub hub or at the venue.  The fee�s on ticket master almost double the cost of the ticket.

**Comment by mikeal** [comment]
Saturday is good for me too :)

**Comment by mikeal** [comment]
Quick update on the start/end time.

One of my neighbors through a giant party their first weekend in the warehouse. Bass was still thumbing at like 3am and one of the other units had to get them to shut it down and the people throwing the party were less than pleasant. 

As a result the owners of the building are doubling down on the lease terms which start "quiet hours" at 10pm.

So, I think that we should _start_ as soon as possible (probably right as it is getting dark) and we should lock down an after hours "RaveJS" if we can still use that other space in west oakland.

**Comment by mikeal** [comment]
Sunset is roughly 7:15pm. We could "start" at 6pm (people showing up and mulling around) do talks at 7:30-8pm and then two hours of dance before we have to close it down and direct people to the after party.

**Comment by MylesBorins** [comment]
This could work. Did we still want to meet Saturday?

**Comment by mikeal** [comment]
Yes, we should still meet Saturday to set stuff up and figure out any remaining cables or equipment we might need :) Also, if we setup all the gear nobody has to get there early on the 28th to do it :)

**Comment by MylesBorins** [comment]
Amazing! Time and address? Should we send this out as a dm or email?

**Comment by mikeal** [comment]
How about noon, I'll order lunch, 1035 22nd Ave, Unit 11, Oakland, 94606.

Use Google Maps because Apple Maps will put you on the wrong side of the freeway :) If you take an Uber they'll get to it fine tho :)

**Comment by bcoe** [comment]
@mikeal noon works for me.

I wonder if we could get away with starting earlier, do more of a block party feel this dance.js?
- start at like 3 or 4PM.
- have drinks available.
- bring in pizza for dinner.
- play the nighttime set until 10.

**Comment by bcoe** [comment]
FYI, just locked in the robot.

**Comment by MylesBorins** [comment]
Node school SF is running from 1-5

I volunteered as a mentor, and was planning to try and bring the attendees
with to dance as an after party.

That being said, if an afternoon thing is the best idea don't hold off on
my account.

**Comment by bcoe** [comment]
@TheAlphaNerd we would still run the dance until as late as possible, but I think moving things earlier would help us have more of a musical arc to the afternoon/evening -- which I think has lacked at our first couple events as much as it could.

Having the extra node school attendees would help the late game :)

**Comment by bcoe** [comment]
@TheAlphaNerd perhaps pizza break at 6, talks at 7; so that you can make it in time to speak?

**Comment by nebrius** [comment]
I love the idea of a block party + 🍕

**Comment by bcoe** [comment]
@bryan-m-hughes, @mikeal, @TheAlphaNerd, @dshaw has kindly offered for NodeSource to provision pizza for March 28th.

**Comment by mikeal** [comment]
We could start with a little audio hackathon. Maybe 3pm - 6pm is audio hack time and then we encourage lots of people to show up at 6pm?

**Comment by othiym23** [comment]
Get something that's not 100% pork plz today, cuz I'm coming over as well. Is it faster to BART to Fruitvale or 14th St?

**Comment by bcoe** [comment]
CC: @dshaw @othiym23 @gsilk @TheAlphaNerd @emilyrose.

having gone on an adventure to @mikeal's place on the weekend to setup audio-equipment , I have a thought about the event on March 28th. What if we rent a shuttle bus and give people a lift from 12th Street Bart to Mikeal's throughout the evening? I think this would help turn out a ton.

Does anyone have experience with this, what companies have people used for past Node events?

In other news, ticket sales are sub-optimal so far; I'm working on a mix to try to draw some attention to the events, any other ideas -- we should start pressing people:

https://ti.to/dancejs/dancejs-march-28th?release_id=ircb-kxmrdo

**Comment by bcoe** [comment]
looping @jameswomack in on this thread, who would love to perform on the 28th.

**Comment by jameswomack** [comment]
Thanks @bcoe. Yes, I'd love to do a funk set. I can try to get more people to show up by 1) sharing the event within Netflix’s Node & JS groups and 2) posting a mix to my SoundCloud account.

**Comment by mikeal** [comment]
> shuttle bus

We have like 12 people signed up right now, renting a shuttle bus sounds like a bit much. Also, with the whole block party thing happening I think that we should expect people to filter in on a much longer timeline so it would have to be doing constant runs to check for people over like 6 hours.

I think the whole "close to Bart thing" is far less important than we're making it out to be. People who live in the area bike or drive and the rest tend to take Uber (anecdotal from the last event, but a new Uber showed up every 2 minutes for the first hour).

What I'm actually more worried about is the fact that Apple Maps directs people to the wrong side of the freeway. That's concerning. We need to put in big bold letters "USE GOOGLE MAPS" and "Uber routes fine" :)

**Comment by bcoe** [comment]
@mikeal for the record, we're up to 28 tickets sold now -- and we're starting to try to ramp up the promotion. I have had a few negative responses to location so far, Cambi is going to sit this one out, and I just had this conversation with @rockbot:

```
benjamincoe [10:58 AM] 
want to come to this: http://dancejs.io/
I'm trying to get people to grab tickets so that I have a better idea of #s.
rockbot [11:02 AM] 
it's a mikeal's scary warehouse location, yes?
rockbot [11:03 AM]
chances are unfortunately low :disappointed:
benjamincoe [11:03 AM] 
it's actually a lovely part of town.
```

I understand your point that a shuttle is overkill., but I think we do need to find a way to reassure people that it's not that hard to get to the location -- I think we should reach out to all prior Dance.js attendees soon: with a message about transportation, and to try to sell a few more tickets.

@jameswomack a mini-mix would be awesome, we've done this at prior events and it's a good way to get people tweeting -- I'm actually working on one myself as well.

In other news, @jameswomack we should get you up on the website:

https://github.com/dancejs/dancejs.io

Also, @zeke, I seem to have broken the website horribly in Safari :(

**Comment by jameswomack** [comment]
@bcoe I'll create a mini-mix and open a PR adding myself to the site this evening

**Comment by mikeal** [comment]
@bcoe one thing you could do is say "For your convenience we're shuttling people from 12th st Bart at these times: 3pm, 4pm, 6pm, 6:10pm, ..." 

You could probably do that in Gabe's van, I doubt a ton of people will be at each one. Question: Can we paint "DanceJS" on the side of his van? :P

**Comment by mikeal** [comment]
@bcoe you may want to consider shuttling from West Oakland instead because during times of high traffic it's probably faster to get to and is a bit more accommodating of shuttles and whatnot.

**Comment by bcoe** [comment]
Pretty awesome news, ElementTheCity a killer DJ who works at rdio reached out to me. He'd like to play next Saturday. Here's his details:

https://twitter.com/elementthecity
https://soundcloud.com/elementthecity

I think this is a good opportunity for us to really perfect the music portion of the evening. It's also a great opportunity for cross-promotion. Let's get some more tickets sold!

**Comment by jameswomack** [comment]
Nice, that is good news. We should put together a schedule.

**Comment by bcoe** [comment]
@jameswomack agreed, I promised ELEMENT I'd get him a schedule tomorrow so that he can prep. Perhap some of us can hop in the npm or node IRC tomorrow and discuss the schedule? My obsessive-compulsive goal for this Dance.js is to really dial in the overall arc of the event.

**Comment by bcoe** [comment]
How does this sound for an event lineup/description? I'm working on something I can send out to our mailing list of prior attendees:

You're invited to a nerdy block party with the Dance.js crew.

4:30PM - 10:30PM,
1035 22nd Ave, Oakland
(a short Uber from 12th street BART).

There'll be:
- a music/lighting hack: brought to you by npm and Spark.
- beverages and dancing robots provided by rdio.
- a dinner provisioned by our good friends at NodeSource.

The lineup thus far:

4:30PM - 5:30PM A DJ Set By C J Silverio.
5:30PM - 6:30PM A DJ Set By Gabriel Silk.
6:30PM - 7:00PM show off your hacks
7:00PM - 7:20PM Bryan Hughes, will be talking about the rdio API.
7:25PM - 7:45PM Myles Borins, giving a talk about Sampling Theory
8:00PM - 8:40PM A DJ Set By Ben Coe
8:40PM - 9:40PM A DJ Set By James Womack
9:40PM - (When Mikeal Shuts Us Down) Forrest Norvell

There'll be drinks, fun gadgets to play with, wonderful people, and
dancing robots.

CC: @dshaw, @emilyrose, @mikeal, @othiym23, @bryan-m-hughes, @TheAlphaNerd, @ceejbot.

**Comment by bcoe** [comment]
also CCing @jameswomack to the lineup above.

**Comment by nebrius** [comment]
Hey, sorry for not getting to this sooner, I've been AFK since yesterday afternoon. It's a bit late now, I know, but the last paragraph probably should have included a mention of food in the last paragraph in addition to drinks, etc.

**Comment by bcoe** [comment]
@bryan-m-hughes shoot, unfortunately shipped it already. we do mention:

`a dinner provisioned by our good friends at NodeSource.`

So hopefully people will catch that line.

**Comment by bcoe** [comment]
I'm really excited about @mikeal's hacking idea., it will be a good way to get people interacting with each other as we start to ramp up the excitement for the talks, culminating in the performances., and the dancing robots -- figure we'll get people hacking as they show up, around 4:30PM., and then let people show off anything cool they make prior to talks?
- @emilyrose has offered to bring some spark cores for people to play with.
- @HarleyKwyn might be able to provide some Tessels for people to play with.
- @mikeal do you have those music-making, circuit-thingamajigs we could let people play with again?

It would be pretty cool if people could hack on something lighting related., which could potentially add to the performances later.

**Comment by MylesBorins** [comment]
Did someone say [Hackathon???](http://vooza.com/videos/hackathon/)

**Comment by bcoe** [comment]
@TheAlphaNerd it's not  Hackathon, it's an interactive performance expressed through the medium of hardware devices provided by several of our sponsors.

**Comment by MylesBorins** [comment]
Can we make [kinetic sculptures](https://www.youtube.com/watch?v=dehXioMIKg0)?

**Comment by affinity-matrix** [comment]
littleBits would be fun!

@TheAlphaNerd we could certainly get started with kinetic sculpture!

**Comment by kwyn** [comment]
Definitely can bring some Tessels! I'll do my best to get some neopixels strips as well. Just hope we won't have to do much soldering since the last few batches I got from Adifruit the leads were soldered to the out pins.

If you have some neopixels bring them, for blinky flashy things.

**Comment by MylesBorins** [comment]
That was a fun day wasn't it
