### ISSUE TITLE
Visuals!

### ISSUE THREAD

**Issue by davidguttman** [dancejs/Oakland#3]
Sound reactive visuals would be sweet.

Will there be a projector / audio feed?

**Comment by MylesBorins** [comment]
This sounds awesome!!! @bcoe what do you think?

**Comment by bcoe** [comment]
@davidguttman @TheAlphaNerd sorry for the slow response, it's been a hectic couple weeks!

I would love to have sound-reactive visuals, there will be a projector, and we should be able to provide any audio connections necessary.

Are you going to be here for JSFest @davidguttman, want to help with this?

**Comment by davidguttman** [comment]
Awesome, I'll be there and would love to help! 

Thinking of how I can tie it in with my talk: https://github.com/jsfest/oakland-cfp/issues/103

**Comment by bcoe** [comment]
@davidguttman awesome! perhaps you can help with the load in on December 13th, it would be great to have someone help take point on setting up the visuals.

Our current equipment list is here:

https://github.com/nexxy/ravejs (in the README).

And there's a wish list here, regarding purchases for the next event:

https://github.com/dancejs/Oakland/issues/4

See any glaring omissions that would help with setting up the visuals you're thinking of (note, we do have access to a projector which we used at the last event).

**Comment by affinity-matrix** [comment]
hey all :) so I've recently started working with @spark, and I think there is tons of potential to use the platform for things like interactive visuals and whatnot. Perhaps we should pick a time to chat about this?

**Comment by MylesBorins** [comment]
What a wonderful idea!!!! I’m super in!

**Comment by davidguttman** [comment]
@bcoe Yep, totally down to help with load in. I looked over the equipment but, really what it comes down to for visuals are long enough power, VGA, and audio cables, as well as a place to set up the projector (and laptop) so that people aren't walking through / getting blinded by it / casting shadows / bumping into it (usually high up)

@nexxy would love to chat about @spark

**Comment by bcoe** [comment]
@davidguttman we've got a projector, cables, and a stand (assuming we can secure it for the 13th), @mikeal are there any other events that will need the projector on the Saturday?

@davidguttman this should give you an idea of the layout:

https://www.dropbox.com/sh/rysgf68oe0aq7bi/AAA--6Ya2qs7-3V9UX4DxODra/dance-js_10042014_005.jpg?dl=0

**Comment by aulvi** [comment]
@nexxy send me free shit!!

**Comment by affinity-matrix** [comment]
@aulvi you know I will :) 

@davidguttman we should sync up sometime! I hear you're friends with one of my new co-workers!

**Comment by mikeal** [comment]
No other Saturday event should need the projector.

**Comment by flyingoctopus** [comment]
if anybody has a copy of vdmx lying around @TheAlphaNerd should have my collection moons ago. Almost all sound reactive fun times.
