### ISSUE TITLE
Dance.js Vancouver Edition

### ISSUE THREAD

**Issue by bcoe** [dancejs/Oakland#6]
@othiym23 you mentioned there was someone in Canada interested in throwing a Dance.js back in my home land? Would love to get them pulled into this org.

**Comment by othiym23** [comment]
That would be @qard. Stephen, you still interested in making this happen?

**Comment by Qard** [comment]
Yep. Need to check around with some friends to see if there's enough audio hackers in town for it to work. But I'm hopeful. I know there is a code-as-art group of sorts here, which might have some overlap.

**Comment by bcoe** [comment]
@Qard just starting to unbury myself from an infinite pile of work, sorry for not replying earlier! It would be awesome to have a group of likeminded individuals throw an event in Vancouver. Here's our original manifesto, to give you an idea of our motivations:

https://github.com/nexxy/ravejs

Let us know anything we can do to help, myself and I'm sure some others would happily make the trip up for the inaugural event.

**Comment by Qard** [comment]
No worries. At the moment, I'm looking at trying a one-off thing, probably attached to Node Brigade or VanJS. I'm not too sure what the response will be yet.

I know of a handful of audio hackers here. Most seem to be too busy with one thing or another to get involved though. Might have to light some fires under some asses. :)

**Comment by MylesBorins** [comment]
I have a buddy vince in van @flyingoctopus he's involved in maker Faire and
then make audio group. Perhaps he would like to help with finding folks.

Depending on timing maybe I could come up!

**Comment by flyingoctopus** [comment]
Well snap guys, you found me out. Thanks for the mention @TheAlphaNerd. @Qard I def know a good sound tribe out here (& Oakland funnily enough) from Maker Faire to Madrona Labs. We should mindmeld and kill it.

![drop the bass](https://dl.dropboxusercontent.com/u/567408/%3Ab%3A/NHlPF.jpeg)

**Comment by flyingoctopus** [comment]
p.s. supercolider + node. awesome idea or better solution. discuss.

**Comment by Qard** [comment]
I haven't tried supercollider. I've mostly just been playing with baudio/asynth and http://wavepot.com or http://studio.substack.net. I enjoy the learning experience of figuring out what math is used to generate particular sounds as much or more than actually producing something listen-able. :P

Agreed on the melding of minds. I just followed you on Twitter (stephenbelanger), DM me if you want to meet up sometime. :)

**Comment by MylesBorins** [comment]
@flyingoctopus glad to see you here.  Coming to the bay area any time soon?

**Comment by flyingoctopus** [comment]
@TheAlphaNerd thank yo! And always a pleasure to see your sultry face good sir! I had planned on being in Berkeley with the fam for the holidays but I think I need to hunker down here until I sort some work things out. Where you at Feb/March?

**Comment by bcoe** [comment]
@Qard don't suppose you're down for JSFest, or at any other point in the near future? otherwise, let's Skype sometime with some of the Oakland Dance.js people :+1:

we're going to be pretty swamped pulling everything together for next weekend, but after that I think we'd like to talk about what meet ups look like going forward.

**Comment by Qard** [comment]
Yep, I'll be at JSFest. I'm presenting at the browserified event on Monday, actually. I'll be down for the whole week though. :)

**Comment by Qard** [comment]
Vancouver DanceJS now has it's own repo at https://github.com/dancejs/Vancouver. It's all official and stuff. Let's move conversation there.
