### ISSUE TITLE
Dance.js Forward.js edition

### ISSUE THREAD

**Issue by MylesBorins** [dancejs/Oakland#7]
I ran into Dave Nugent tonight and was talking about the upcoming [forward js](http://forwardjs.com/) summit and the idea of have a dance.js event was proposed.  Assuming there are no logistic problems on there end would ya'll be up for having a dance party on the other side of the bridge?

This is happening Feb 4th

**Comment by drnugent** [comment]
As an FYI we have a room reserved and we can set up A/V equipment as necessary. We'll already have speakers and a screen in the room.

**Comment by bcoe** [comment]
@TheAlphaNerd perhaps we should start a `dancejs/SanFrancisco` repo? This sounds like fun.

**Comment by othiym23** [comment]
I'm up for sound engineering duties, and may or may not be up for taking a DJ slot, depending on how my January goes.

**Comment by MylesBorins** [comment]
closed in lieu of https://github.com/dancejs/San-Francisco/issues/1
