### ISSUE TITLE
Dance.js JSFest Final Countdown

### ISSUE THREAD

**Issue by bcoe** [dancejs/Oakland#8]
Just a couple days to go before Dance.js, wanted to keep everyone in the loop:
## Highlights
- we're in the awesome 25C space again (directly behind the parkway).
  - there's a winery on-site that will be providing drinks.
- we've bought new audio-equipment (the stereo cutting out should be  thing of the past).
- thanks to @nexxy Spark is going to provide equipment for lighting!
- we've bought stickers, they should be arriving today.http://hexb.in/
- the robot will again be making an appearance:.
## The Lineup
- **2PMish:** @gsilk, @mikeal, and I will grab equipment out of storage and do some sorting.
- **4PM:** meet at 25C (behind the parkway) to begin setting up:
  - @othiym23: is our audio-engineer again, and will be overseeing equipment setup.
  - @nexxy and @davidguttman will take point on lighting.
- **5PM:** theAnita's Dropship will arrive and begin setting up (@kasima will be the contact).
- **6PM:** @ceejbot will be playing some ambient music, while peple arrive.
- **7PM:** Anita's DropShip will given a 20 minute presentation.
  - there'll be an interlude afterwords, which will give people a chance to play with the Dropship.
- **7:45PM:** @gsilk will be giving his talk, on the topic of creating generative music via Emacs.
  - Gabe will also play a set.
- **8:45PM:** I figure I'll play a set?
- **9:45PM:** **we could use another DJ for this block, can anyone think of someone who'd be interested in playing a bit of a pop set? CC: @seldo**
- **10:30PM - ~11:15PM** I was thinking we could open up the stage to collaboration and play: @NHQ this would be a great time to crack out the drum, @substack you said you might want to play?, @TheAlphaNerd?, @obensource?
- **11:15PM:** we've got to cleanup.
- **11:30PM:** there's a warehouse space we could potentially use for an after-party, but I don't know how organized this is (@gsilk?).
## What needs to be done day of?
- _it would be great to have a few people help with setup:_ @linclark? @zeke 
- _we need food:_ @maxogden you wanted to bring in some food? I think it would also be good to have some munchies around like cookies and crackers.
- _how should we run the bar?:_ @mikeal I think it might be cool to write a check for the cash bar minimum ($500) and then go to charging per-drink after.
  - there will be beer and wine available.
  - credit-card and cash will be accepted once we hit the $500.
- _we need to write a check for the robot again_: CC: @mikeal
- _there's new audio equipment:_ we bought a new compressor/limiter and a new amp for the sub.
  - there's a known issue with the subwoofer, @othiym23 the new amp does not isolate the bass frequency so if we put a direct line into the subwoofer it causes issues. We need a way to isolate the frequency of the audio input going into the subwoofer.

**phew**, long post, but that's everything currently on my mind.

**Comment by max-mapper** [comment]
@bcoe whats the food budget?

**Comment by bcoe** [comment]
@maxogden that's a great question, what do you think @mikeal? I'll be at Oakland.js tonight if we don't sort this out here :+1:

**Comment by affinity-matrix** [comment]
I'm more than happy to fill in with a 9:45 set if nobody else wants to step up.

**Comment by seldo** [comment]
+1 for pop music :-p Not everyone likes EDM, folks.

**Comment by bcoe** [comment]
@nexxy would love to have you play that slot, let's make it official I'll update the site tonight.

**Comment by affinity-matrix** [comment]
sounds good! Please send requests for some pop tunes to throw into the mix! I will try to focus on high danceability, big hits & doing requests (at my discretion).

**Comment by max-mapper** [comment]
https://www.youtube.com/watch?v=32FB-gYr49Y

**Comment by affinity-matrix** [comment]
@maxogden added to the list!

**Comment by MylesBorins** [comment]
I’m super easy going, would love to play but also would love to give others the chance.

You mentioned the jam time later… also really into that.

I’ll come prepared to play either.  I have some pop music I can throw on too.=

**Comment by MylesBorins** [comment]
ALSO… I’m supra into the idea of the warehouse party.  I might not be able to get to the event early as I’ll be helping with nodebots, but I’d be willing to leave dance.js early to help set up things over at the warehouse (especially if I’m not performing)=

**Comment by davidguttman** [comment]
Anyone have a long USB extension? Could give more flexibility with where we
put the midi controller to play with the visuals

**Comment by othiym23** [comment]
@mikeal Can we next-day an active crossover? Behringer makes 3 or 4 that Amazon should have in stock, and that would fix the bass cabinet issues Ben was describing. I can get you a part number / URL later tonight. Should be under $200.

**Comment by bcoe** [comment]
@othiym23 @mikeal getting one of these units sent overnight would be awesome, otherwise I think we might need to send someone to Guitar Center day of.

@othiym23 I believe we have two mixers, could we figure out some creative wiring day of? (Worst case scenario).

**Comment by bcoe** [comment]
Note to self, we also need to make sure we bring ice Saturday, as the bar does not have any.

**Comment by kasima** [comment]
We're incredibly excited to present Anita's Dropship this saturday. We have hit a snafu that we're scrambling to resolve. We could use some help. It seems that our app is only working under iOS 7 on a device with an A7 chip. Our dev doesn't have time to figure out iOS 8. Unfortunately, we've all updated our devices.

I have some leads but haven't gotten a device in hand yet. If anyone has access to an A7 device that is still on iOS 7 that we could borrow as soon as possible up through the event, that would help a ton. It could be:
- iPhone 5S
- iPad Air
- iPad Mini (Retina)

Thanks, all!

**Comment by bcoe** [comment]
@kasima I have an old iPad I don't use. It appears to be on 6.1.3, might this work?

**Comment by kasima** [comment]
@bcoe - Alas, it's gotta be iOS 7. We never tested it on iOS 6 and with the way Apple controls firmware upgrades, it would jump to iOS 8. I'm picking one up tomorrow. Thanks though!

**Comment by mikeal** [comment]
too late for next day, is there somewhere local we can buy?

**Comment by bcoe** [comment]
@mikeal let's just take stock of what we have on the day of, and make a run to Guitar Center if it's required.

**Comment by kasima** [comment]
@bcoe Is there a projector we can plug into? We have a video from our composer going over how the generative music is put together.

**Comment by bcoe** [comment]
@kasima yes, there will be a projector :+1:

**Comment by bcoe** [comment]
CC: @kasima, @Qard, @ceejbot, @gsilk, @othiym23, @maxogden, @linclark, @davidguttman, @nexxy, @fotoverite

Thanks to everyone who spoke, helped setup, gave a talk, or performed yesterday. Many hands made for light lifting, and I felt that the event went great (even with the protests giving a somewhat Orwellian, vibe to the night).

Special thanks to @othiym23, who kept the sound system running even with various power-outages and other nuisances. And to Anita's Dropship who gave an amazing keynote talk :+1:

@fotoverite would love to have some photos of the event for the website, and to share with the 25C venue (if that's alright). Mind posting a few here when you've processed them?

**Comment by gsilk** [comment]
Second that -- thanks to everyone for making this awesome event happen. I'm excited for the next one!

**Comment by kasima** [comment]
Thanks again for having us. So great to be a part of it. :sparkles:

**Comment by othiym23** [comment]
@kasima It was fantastic having you all there – it's a seriously impressive project, and we probably should have had you all speak last because I'm pretty sure people could have played with the Dropship all night! Thanks for coming!

Since the event is over and we're already looking to the next DanceJS, I'm going to close out this issue. I'm just echoing everybody else, but thanks to everyone involved, especially @bcoe for his tireless efforts in making DanceJS happen.
